"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Container from "@/components/container";
import { Provider } from "react-redux";
import { store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Movie Review App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body
          className={`${inter.className} bg-zinc-100 text-zinc-900 min-h-screen`}
        >
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
        </body>
      </html>
    </Provider>
  );
}
