export const genre = [
  { label: "Action", value: "Action" },
  { label: "Crime", value: "Crime" },
  { label: "Comedy", value: "Comedy" },
  { label: "Animation", value: "Animation" },
  { label: "Drama", value: "Drama" },
  { label: "Horror", value: "Horror" },
  { label: "Biography", value: "Biography" },
  { label: "Adventure", value: "Adventure" },
  { label: "Thriller", value: "Thriller" },
  { label: "Romance", value: "Romance" },
  { label: "Western", value: "Western" },
  { label: "Mystery", value: "Mystery" },
  { label: "Short", value: "Short" },
  { label: "Fantasy", value: "Fantasy" },
  { label: "Family", value: "Family" },
  { label: "Reality-TV", value: "Reality-TV" },
  { label: "Documentary", value: "Documentary" },
  { label: "Musical", value: "Musical" },
  { label: "Game-Show", value: "Game-Show" },
  { label: "Sci-Fi", value: "Sci-Fi" },
  { label: "Talk-Show", value: "Talk-Show" },
  { label: "History", value: "History" },
  { label: "Music", value: "Music" },
  { label: "Sport", value: "Sport" },
  { label: "War", value: "War" },
  { label: "Film-Noir", value: "Film-Noir" },
  { label: "News", value: "News" },
];

export const type = [
  { label: "Film", value: "Film" },
  { label: "Series", value: "Series" },
];

export const certificate = [
  { label: "PG-13", value: "PG-13" },
  { label: "R", value: "R" },
  { label: "TV-MA", value: "TV-MA" },
  { label: "TV-14", value: "TV-14" },
  { label: "TV-PG", value: "TV-PG" },
  { label: "PG", value: "PG" },
  { label: "TV-G", value: "TV-G" },
  { label: "(Banned)", value: "(Banned)" },
  { label: "Not Rated", value: "Not Rated" },
  { label: "E", value: "E" },
  { label: "NC-17", value: "NC-17" },
  { label: "TV-Y7-FV", value: "TV-Y7-FV" },
  { label: "TV-Y7", value: "TV-Y7" },
  { label: "Unrated", value: "Unrated" },
  { label: "Approved", value: "Approved" },
  { label: "G", value: "G" },
  { label: "TV-Y", value: "TV-Y" },
  { label: "GP", value: "GP" },
  { label: "Passed", value: "Passed" },
  { label: "M", value: "M" },
  { label: "X", value: "X" },
  { label: "M/PG", value: "M/PG" },
];

export const ratings = [
  { label: "10 Stars", value: "10" },
  { label: "9 Stars", value: "9" },
  { label: "8 Stars", value: "8" },
  { label: "7 Stars", value: "7" },
  { label: "6 Stars", value: "6" },
  { label: "5 Stars", value: "5" },
  { label: "4 Stars", value: "4" },
  { label: "3 Stars", value: "3" },
  { label: "2 Stars", value: "2" },
  { label: "1 Star", value: "1" },
];
