export const genre = [
  { label: "Action", value: "action" },
  { label: "Crime", value: "crime" },
  { label: "Comedy", value: "comedy" },
  { label: "Animation", value: "animation" },
  { label: "Drama", value: "drama" },
  { label: "Horror", value: "horror" },
  { label: "Biography", value: "biography" },
  { label: "Adventure", value: "adventure" },
  { label: "Thriller", value: "thriller" },
  { label: "Romance", value: "romance" },
  { label: "Western", value: "western" },
  { label: "Mystery", value: "mystery" },
  { label: "Short", value: "short" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Family", value: "family" },
  { label: "Reality-TV", value: "reality-tv" },
  { label: "Documentary", value: "documentary" },
  { label: "Musical", value: "musical" },
  { label: "Game-Show", value: "game-show" },
  { label: "Sci-Fi", value: "sci-fi" },
  { label: "Talk-Show", value: "talk-show" },
  { label: "History", value: "history" },
  { label: "Music", value: "music" },
  { label: "Sport", value: "sport" },
  { label: "War", value: "war" },
  { label: "Film-Noir", value: "film-noir" },
  { label: "News", value: "news" },
];

export const type = [
  { label: "Film", value: "film" },
  { label: "Series", value: "series" },
];

export const certificate = [
  { label: "PG-13", value: "pg-13" },
  { label: "R", value: "r" },
  { label: "TV-MA", value: "tv-ma" },
  { label: "TV-14", value: "tv-14" },
  { label: "TV-PG", value: "tv-pg" },
  { label: "PG", value: "pg" },
  { label: "TV-G", value: "tv-g" },
  { label: "(Banned)", value: "banned" },
  { label: "Not Rated", value: "not-rated" },
  { label: "E", value: "e" },
  { label: "NC-17", value: "nc-17" },
  { label: "TV-Y7-FV", value: "tv-y7-fv" },
  { label: "TV-Y7", value: "tv-y7" },
  { label: "Unrated", value: "unrated" },
  { label: "Approved", value: "approved" },
  { label: "G", value: "g" },
  { label: "TV-Y", value: "tv-y" },
  { label: "GP", value: "gp" },
  { label: "Passed", value: "passed" },
  { label: "M", value: "m" },
  { label: "X", value: "x" },
  { label: "M/PG", value: "m-pg" },
];

export const ratings = [
  { label: "10 Stars", value: "10" },
  { label: "9 Stars", value: "9" },
  { label: "8 Stars", value: "8" },
  { label: "7 Stars", value: "7" },
  { label: "6 Stars", value: "6" },
  { label: "5 Stars", value: "5" },
  { label: "4 Stars", value: "4" },
  { label: "3 Stars", value: "3" },
  { label: "2 Stars", value: "2" },
  { label: "1 Star", value: "1" },
];
