export const titles = [
  "No Time to Die",
  "The Guilty",
  "The Many Saints of Newark",
  "Venom: Let There Be Carnage",
  "Dune",
  "Ted Lasso",
  "Free Guy",
  "House of the Dragon",
  "What If...?",
  "Sex Education",
  "The Walking Dead",
  "The Chestnut Man",
  "Foundation",
  "The Sopranos",
  "Only Murders in the Building",
  "American Horror Story",
  "Seinfeld",
  "Grey's Anatomy",
  "Game of Thrones",
  "Black Widow",
  "The Last Duel",
  "Alice in Borderland",
  "Shang-Chi and the Legend of the Ten Rings",
  "Billions",
  "Resident Evil: Welcome to Raccoon City",
  "Spectre",
  "Casino Royale",
  "Lucifer",
  "The Morning Show",
  "Halloween Kills",
  "There's Someone Inside Your House",
  "Malignant",
  "Wolf",
  "La casa de papel",
  "Tick, Tick... Boom!",
  "The Night House",
  "Succession",
  "La Brea",
  "Venom",
  "Skyfall",
  "NCIS: Naval Criminal Investigative Service",
  "See",
  "The Addams Family 2",
  "Big Sky",
  "Peaky Blinders",
  "What We Do in the Shadows",
  "Titane",
  "American Crime Story",
  "CSI: Vegas",
  "Stranger Things",
  "Titans",
  "Goliath",
  "Breaking Bad",
  "On My Block",
  "Old",
  "Y: The Last Man",
  "The Rookie",
  "No One Gets Out Alive",
  "Law & Order: Special Victims Unit",
  "Hocus Pocus",
  "The Office",
  "Chicago Fire",
  "Dune",
  "You",
  "Den skyldige",
  "Quantum of Solace",
  "Doom Patrol",
  "Yellowstone",
  "The Suicide Squad",
  "Friends",
  "Eternals",
  "Brooklyn Nine-Nine",
  "Cruella",
  "The Blacklist",
  "Supernatural",
  "Downton Abbey",
  "Animal Kingdom",
  "Criminal Minds",
  "Halloween",
  "Vigil",
  "Infinite",
  "V/H/S/94",
  "The Good Doctor",
  "Dexter",
  "The Green Knight",
  "Last Man Down",
  "The French Dispatch",
  "The Boys",
  "Ridley Road",
  "Vikings",
  "Spider-Man: No Way Home",
  "Silent Witness",
  "Ghosts",
  "The Card Counter",
  "Lamb",
  "Midsomer Murders",
  "Rick and Morty",
  "After We Fell",
  "Riverdale",
  "The Harder They Fall",
  "Licorice Pizza",
  "Chicago Med",
  "The Lost Symbol",
  "Star Wars: Visions",
  "Promising Young Woman",
  "Modern Family",
  "The Mandalorian",
  "Queenpins",
  "The Big Bang Theory",
  "The Wire",
  "Doctor Who",
  "Candyman",
  "The White Lotus",
  "The Witcher",
  "The Starling",
  "Kate",
  "The Sandman",
  "Knives Out",
  "New Amsterdam",
  "Cry Macho",
  "Castle",
  "Black Mirror",
  "Law & Order: Organized Crime",
  "Till Death",
  "The Voyeurs",
  "The Crown",
  "Better Call Saul",
  "The Handmaid's Tale",
  "Lost",
  "Outlander",
  "The Simpsons",
  "Dear Evan Hansen",
  "CSI: Crime Scene Investigation",
  "Loki",
  "It's Always Sunny in Philadelphia",
  "Hypnotic",
  "Superstore",
  "The Resident",
  "Gisaengchung",
  "Mr. Robot",
  "Last Night in Soho",
  "Titanic",
  "Shiddat",
  "Scream",
  "Ozark",
  "Rise of the Footsoldier: Origins",
  "F9",
  "Shingeki no kyojin",
  "365 dni",
  "Archer",
  "How I Met Your Mother",
  "Chehre",
  "Young Sheldon",
  "The Batman",
  "Black Mafia Family",
  "Manifest",
  "S.W.A.T.",
  "Friday Night Lights",
  "9/1/2001",
  "Heat",
  "Old Henry",
  "Chicago P.D.",
  "Shameless",
  "The Expanse",
  "Muppets Haunted Mansion",
  "Westworld",
  "American Rust",
  "Ghosts",
  "Fear the Walking Dead",
  "Cinderella",
  "Bridgerton",
  "Halloween",
  "The Addams Family",
  "House M.D.",
  "Good Girls",
  "The Flash",
  "Scream",
  "Suits",
  "Once Upon a Time... in Hollywood",
  "My Little Pony: A New Generation",
  "Jungle Cruise",
  "Gilmore Girls",
  "True Detective",
  "Bones",
  "American Horror Stories",
  "Intrusion",
  "Leverage: Redemption",
  "Blade Runner 2049",
];
