export const titles = [
  "No Time to Die",
  "The Guilty",
  "The Many Saints of Newark",
  "Venom: Let There Be Carnage",
  "Dune",
  "Ted Lasso",
  "Free Guy",
  "House of the Dragon",
  "What If...?",
  "Sex Education",
  "The Walking Dead",
  "The Chestnut Man",
  "Foundation",
  "The Sopranos",
  "Only Murders in the Building",
  "American Horror Story",
  "Seinfeld",
  "Grey's Anatomy",
  "Game of Thrones",
  "Black Widow",
  "The Last Duel",
  "Alice in Borderland",
  "Shang-Chi and the Legend of the Ten Rings",
  "Billions",
  "Resident Evil: Welcome to Raccoon City",
  "Spectre",
  "Casino Royale",
  "Lucifer",
  "The Morning Show",
  "Halloween Kills",
  "There's Someone Inside Your House",
  "Malignant",
  "Wolf",
  "La casa de papel",
  "Tick, Tick... Boom!",
  "The Night House",
  "Succession",
  "La Brea",
  "Venom",
  "Skyfall",
  "NCIS: Naval Criminal Investigative Service",
  "See",
  "The Addams Family 2",
  "Big Sky",
  "Peaky Blinders",
  "What We Do in the Shadows",
  "Titane",
  "American Crime Story",
  "CSI: Vegas",
  "Stranger Things",
  "Titans",
  "Goliath",
  "Breaking Bad",
  "On My Block",
  "Old",
  "Y: The Last Man",
  "The Rookie",
  "No One Gets Out Alive",
  "Law & Order: Special Victims Unit",
  "Hocus Pocus",
  "The Office",
  "Chicago Fire",
  "Dune",
  "You",
  "Den skyldige",
  "Quantum of Solace",
  "Doom Patrol",
  "Yellowstone",
  "The Suicide Squad",
  "Friends",
  "Eternals",
  "Brooklyn Nine-Nine",
  "Cruella",
  "The Blacklist",
  "Supernatural",
  "Downton Abbey",
  "Animal Kingdom",
  "Criminal Minds",
  "Halloween",
  "Vigil",
  "Infinite",
  "V/H/S/94",
  "The Good Doctor",
  "Dexter",
  "The Green Knight",
  "Last Man Down",
  "The French Dispatch",
  "The Boys",
  "Ridley Road",
  "Vikings",
  "Spider-Man: No Way Home",
  "Silent Witness",
  "Ghosts",
  "The Card Counter",
  "Lamb",
  "Midsomer Murders",
  "Rick and Morty",
  "After We Fell",
  "Riverdale",
  "The Harder They Fall",
  "Licorice Pizza",
  "Chicago Med",
  "The Lost Symbol",
  "Star Wars: Visions",
  "Promising Young Woman",
  "Modern Family",
  "The Mandalorian",
  "Queenpins",
  "The Big Bang Theory",
  "The Wire",
  "Doctor Who",
  "Candyman",
  "The White Lotus",
  "The Witcher",
  "The Starling",
  "Kate",
  "The Sandman",
  "Knives Out",
  "New Amsterdam",
  "Cry Macho",
  "Castle",
  "Black Mirror",
  "Law & Order: Organized Crime",
  "Till Death",
  "The Voyeurs",
  "The Crown",
  "Better Call Saul",
  "The Handmaid's Tale",
  "Lost",
  "Outlander",
  "The Simpsons",
  "Dear Evan Hansen",
  "CSI: Crime Scene Investigation",
  "Loki",
  "It's Always Sunny in Philadelphia",
  "Hypnotic",
  "Superstore",
  "The Resident",
  "Gisaengchung",
  "Mr. Robot",
  "Last Night in Soho",
  "Titanic",
  "Shiddat",
  "Scream",
  "Ozark",
  "Rise of the Footsoldier: Origins",
  "F9",
  "Shingeki no kyojin",
  "365 dni",
  "Archer",
  "How I Met Your Mother",
  "Chehre",
  "Young Sheldon",
  "The Batman",
  "Black Mafia Family",
  "Manifest",
  "S.W.A.T.",
  "Friday Night Lights",
  "9/1/2001",
  "Heat",
  "Old Henry",
  "Chicago P.D.",
  "Shameless",
  "The Expanse",
  "Muppets Haunted Mansion",
  "Westworld",
  "American Rust",
  "Ghosts",
  "Fear the Walking Dead",
  "Cinderella",
  "Bridgerton",
  "Halloween",
  "The Addams Family",
  "House M.D.",
  "Good Girls",
  "The Flash",
  "Scream",
  "Suits",
  "Once Upon a Time... in Hollywood",
  "My Little Pony: A New Generation",
  "Jungle Cruise",
  "Gilmore Girls",
  "True Detective",
  "Bones",
  "American Horror Stories",
  "Intrusion",
  "Leverage: Redemption",
  "Blade Runner 2049",
  "Selena",
  "Ben 10",
  "Ant-Man and the Wasp: Quantumania",
  "One Foot in the Grave",
  "Waves",
  "Against All Odds",
  "The Chi",
  "The Beastmaster",
  "Scooby Doo, Where Are You!",
  "Janghwa, Hongryeon",
  "Pinocchio",
  "Private Parts",
  "Gräns",
  "Playing with Fire",
  "Moonstruck",
  "Kakegurui",
  "Takers",
  "Child's Play 3",
  "People Just Do Nothing",
  "Legend of the Seeker",
  "Invictus",
  "Rough Night",
  "From Beyond",
  "Better Off Dead...",
  "Head of the Class",
  "Rogue",
  "Ghosts of Mars",
  "The Exception",
  "NOS4A2",
  "Naked",
  "The Color Purple",
  "La grande bellezza",
  "Anger Management",
  "Exam",
  "The Polar Express",
  "Persian Lessons",
  "Kiss the Girls",
  "The Empire",
  "The Bradshaw Bunch",
  "Carnivàle",
  "The Good Dinosaur",
  "All-Star Weekend",
  "Quo vadis, Aida?",
  "Night Shift",
  "The Unit",
  "Bad Moms",
  "We Hunt Together",
  "Cure",
  "Bangkok Breaking",
  "Taken 3",
  "Rogue",
  "The Great Raid",
  "Knight of Cups",
  "Starsky & Hutch",
  "Endangered Species",
  "Flight of the Phoenix",
  "Spidey and His Amazing Friends",
  "Unthinkable",
  "Kara Para Ask",
  "Summer of 84",
  "Two Weeks in Another Town",
  "Half Baked",
  "The New World",
  "Hung",
  "Shoot 'Em Up",
  "Daybreak",
  "Keeping Up Appearances",
  "La región salvaje",
  "Guilty",
  "The Loud House",
  "Turning Red",
  "Vantage Point",
  "Wishmaster",
  "WKRP in Cincinnati",
  "Leap Year",
  "Chitty Chitty Bang Bang",
  "Mean Streets",
  "Riget",
  "Terminator: The Sarah Connor Chronicles",
  "BROS",
  "À l'intérieur",
  "Ich seh, Ich seh",
  "The Silence",
  "Effie Gray",
  "The White Tiger",
  "Where'd You Go, Bernadette",
  "Átame!",
  "White Lines",
  "Eat Pray Love",
  "Miracles from Heaven",
  "Swallow",
  "Bound by Honor",
  "Blockers",
  "Vice Principals",
  "Petticoat Junction",
  "Dragon Rider",
  "McLintock!",
  "Mad Max Beyond Thunderdome",
  "Reign of Fire",
  "Snuff Films",
  "God: Serengeti",
  "The Unforgivable",
  "Trigger Point",
  "Liv and Maddie",
  "I Still Believe",
  "Mr. Bean",
  "Blindspotting",
  "I Feel Pretty",
  "H2O: Just Add Water",
  "A Wife's Nightmare",
  "Passions",
  "Tenacious D in The Pick of Destiny",
  "Star Trek: First Contact",
  "NewsRadio",
  "The Time Traveler's Wife",
  "Mute",
  "Ted Bundy: American Boogeyman",
  "Conviction",
  "The Long Home",
  "Blade Runner: Black Lotus",
  "Chinjeolhan geumjassi",
  "Red Dawn",
  "So I Married an Axe Murderer",
  "A Good Old Fashioned Orgy",
  "The Spectacular Now",
  "Dokutaa Sutoon",
  "The Longest Ride",
  "The Doctor Blake Mysteries",
  "Raising Dion",
  "Hairspray",
  "Paths of Glory",
  "Machete Kills",
  "The Sisterhood of the Traveling Pants",
  "Big Jake",
  "Midnight Sun",
  "Back to School",
  "A Walk Among the Tombstones",
  "Creeped Out",
  "Entourage",
  "The Gift",
  "No mires para abajo",
  "Fatman",
  "The Banana Splits Movie",
  "A Hologram for the King",
  "Hart to Hart",
  "Dollhouse",
  "Zwartboek",
  "Hot Summer Nights",
  "Sharpe",
  "Time Bandits",
  "Detectorists",
  "Bonnie and Clyde",
  "Whitstable Pearl",
  "Dinosaur",
  "Centaurworld",
  "The Adjustment Bureau",
  "Silent Hours",
  "Ice Age: Collision Course",
  "Pink Flamingos",
  "Kiss Kiss Bang Bang",
  "Inhumans",
  "Belle de jour",
  "Three",
  "Mother's Day",
  "Andromeda",
  "The Beguiled",
  "The Void",
  "Carnage",
  "When Hope Calls",
  "Nathan for You",
  "The Hills Have Eyes II",
  "Doctor Doctor",
  "Striptease",
  "Wrath of the Titans",
  "The Naked Gun: From the Files of Police Squad!",
  "Drunk History",
  "Inspector George Gently",
  "Flack",
  "27 Dresses",
  "Selma",
  "Krypton",
  "Kidding",
  "Seberg",
  "Dirty Rotten Scoundrels",
  "Bir Zamanlar Çukurova",
  "Nikita",
  "Breakfast on Pluto",
  "American Gangster Presents: Big 50 - The Delrhonda Hood Story",
  "Bad Blood",
  "Adventureland",
  "WarGames",
  "The White Orchid",
  "Never Back Down",
  "Poltergeist III",
  "Corner Gas",
  "The Princess Diaries 2: Royal Engagement",
  "Bullitt",
  "Kolskaya sverhglubokaya",
  "God's Not Dead",
  "Food Wars: Shokugeki no Soma",
  "Norbit",
  "Bad Hair",
  "Le dernier mercenaire",
  "2 Days in the Valley",
  "Pandorum",
  "Mirzapur",
  "People Just Do Nothing: Big in Japan",
  "Old Yeller",
  "Snabba Cash",
  "The Seventh Victim",
  "2067",
  "Manhattan",
  "Wet Hot American Summer",
  "Fawlty Towers",
  "Hispania, la leyenda",
  "John Q",
  "Persona",
  "The New Addams Family",
  "Glitch",
  "Jay and Silent Bob Strike Back",
  "Night of the Living Dead",
  "Lucky Number Slevin",
  "Strange Days",
  "Where the Wild Things Are",
  "John Tucker Must Die",
  "Newsies",
  "Ratsasan",
  "Trainwreck",
  "Zenra kantoku",
  "The Champ",
  "The Last Inn",
  "Our Father",
  "King Kong",
  "Secret Diary of a Call Girl",
  "The Square",
  "Dragonball Evolution",
  "The Captive",
  "Ryû to sobakasu no hime",
  "Max Payne",
  "The Creed of Violence",
  "Anatomy of a Murder",
  "SAS Australia",
  "4: Rise of the Silver Surfer",
  "King of Thieves",
  "The Dukes of Hazzard",
  "Act Naturally",
  "Antares",
  "Ansatsu kyôshitsu",
  "Priest",
  "Operation Finale",
  "Take Shelter",
  "Las chicas del cable",
  "A Perfect Getaway",
  "Happy Feet",
  "When a Stranger Calls",
  "A House on the Bayou",
  "P.S. I Love You",
  "Monsters vs. Aliens",
  "Friday Night Dinner",
  "Pan Am",
  "Tangerine",
  "Resident Evil: Afterlife",
  "Bad Trip",
  "The Oval",
  "Wycliffe",
  "Gia",
  "The Brood",
  "Night Raiders",
  "Sam & Cat",
  "Roxanne",
  "The Detour",
  "Scooby-Doo! Mystery Incorporated",
  "The Forgiven",
  "America: The Motion Picture",
  "Resort to Love",
  "Killjoys",
  "AVPR: Aliens vs Predator - Requiem",
  "Endings, Beginnings",
  "La cara oculta",
  "Dumb and Dumber To",
  "Brawl in Cell Block 99",
  "Lake Mungo",
  "Alpha",
  "The Kindergarten Teacher",
  "Tenki no ko",
  "Dalkomhan insaenghal",
  "Four Rooms",
  "Tate no Yuusha no Nariagari",
  "Ma Rainey's Black Bottom",
  "My Struggle",
  "The Whole Truth",
  "Mallrats",
  "The Bureau of Magical Things",
  "Mommy",
  "The Assistant",
  "The Personal History of David Copperfield",
  "The Family Man",
  "Elle",
  "Daddy Day Care",
  "Alvin and the Chipmunks: The Road Chip",
  "The Red Sea Diving Resort",
  "Euphoria",
  "The Last of Us",
  "Scream",
  "The Last Witch Hunter",
  "Bad Boys",
  "Twilight",
  "Donnie Darko",
  "Samaritan",
  "Slumdog Millionaire",
  "A Beautiful Mind",
  "X-Men",
  "Joker",
  "Inception",
  "The Shawshank Redemption",
  "The Dark Knight",
  "Pulp Fiction",
  "Fight Club",
  "Forrest Gump",
  "Titanic",
  "The Matrix",
  "Interstellar",
  "Gladiator",
  "The Godfather",
  "Saving Private Ryan",
  "The Silence of the Lambs",
  "The Departed",
  "Schindler's List",
  "Goodfellas",
  "Jurassic Park",
  "Braveheart",
  "The Lion King",
  "The Social Network",
  "Black Swan",
  "The Sixth Sense",
  "The Prestige",
  "Die Hard",
  "Catch Me If You Can",
  "Gone Girl",
  "Blade Runner",
  "Mad Max: Fury Road",
  "Avatar",
  "The Revenant",
  "Her",
  "Moonlight",
  "Spotlight",
  "The Big Lebowski",
  "Trainspotting",
  "American Beauty",
  "The Shape of Water",
  "Django Unchained",
  "The Intouchables",
  "Oldboy",
  "Pan's Labyrinth",
  "Spirited Away",
  "City of God",
  "Your Name",
  "Crouching Tiger, Hidden Dragon",
  "The Lives of Others",
  "A Separation",
  "Amélie",
  "12 Years a Slave",
  "Whiplash",
  "Birdman",
  "The Florida Project",
  "Lady Bird",
  "The Farewell",
  "Jojo Rabbit",
  "Parasite",
  "Nomadland",
  "Promising Young Woman",
  "The Power of the Dog",
  "Minari",
  "Licorice Pizza",
  "Everything Everywhere All at Once",
  "Top Gun: Maverick",
  "Dune",
  "No Time to Die",
  "Spider-Man: No Way Home",
  "The Batman",
  "Black Panther: Wakanda Forever",
  "Doctor Strange in the Multiverse of Madness",
  "Shang-Chi and the Legend of the Ten Rings",
  "Eternals",
  "Thor: Love and Thunder",
  "Ghostbusters: Afterlife",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "Jurassic World: Dominion",
  "The Flash",
  "Aquaman and the Lost Kingdom",
  "The Marvels",
  "Deadpool 3",
  "Fast X",
  "Mission: Impossible – Dead Reckoning Part One",
  "John Wick: Chapter 4",
  "Sonic the Hedgehog 2",
  "Uncharted",
  "Uncharted",
  "The Matrix Resurrections",
  "Kingsman: The Golden Circle",
  "Ready Player One",
  "Pacific Rim",
  "Edge of Tomorrow",
  "Dredd",
  "Kick-Ass",
  "Warcraft",
  "Transformers: Dark of the Moon",
  "Terminator: Genisys",
  "Suicide Squad",
  "Wonder Woman",
  "Shazam!",
  "Zombieland",
  "The Witch",
  "Get Out",
  "A Quiet Place",
  "Hereditary",
  "It Follows",
  "Midsommar",
  "The Babadook",
  "Us",
  "The Conjuring",
  "Sinister",
  "The Invisible Man",
  "The Cabin in the Woods",
  "It",
  "The Purge",
  "Happy Death Day",
  "Scary Stories to Tell in the Dark",
  "Train to Busan",
  "Bird Box",
  "The Night House",
  "Malignant",
  "Old",
  "Barbarian",
  "Smile",
  "Talk to Me",
  "The Nun",
  "The Texas Chainsaw Massacre",
  "Halloween",
  "Child's Play",
  "Scream",
  "Friday the 13th",
  "Nightmare on Elm Street",
  "Saw",
  "Halloween II",
  "Hellraiser",
  "Candyman",
  "The Exorcist",
  "The Shining",
  "Psycho",
  "The Ring",
  "The Grudge",
  "Carrie",
  "Poltergeist",
  "The Descent",
  "The Witch",
  "The Others",
  "The Orphanage",
  "28 Days Later",
  "The Mist",
  "Don’t Breathe",
  "The Autopsy of Jane Doe",
  "Gerald's Game",
  "The Invisible Man",
  "Cam",
  "Mother!",
  "Get Out",
  "The Cabin in the Woods",
  "Happy Death Day",
  "It Follows",
  "Midsommar",
  "Hereditary",
  "A Quiet Place",
  "Train to Busan",
  "Bird Box",
  "The Night House",
  "Malignant",
  "Old",
  "Barbarian",
  "Smile",
  "Talk to Me",
  "The Nun",
  "The Texas Chainsaw Massacre",
  "Halloween",
  "Child's Play",
  "Scream",
  "Friday the 13th",
  "Nightmare on Elm Street",
  "Saw",
  "Halloween II",
  "Hellraiser",
  "Candyman",
  "The Exorcist",
  "The Shining",
  "Psycho",
  "The Ring",
  "The Grudge",
  "Carrie",
  "Poltergeist",
  "The Descent",
  "The Witch",
  "The Others",
  "The Orphanage",
  "28 Days Later",
  "The Mist",
  "Don’t Breathe",
  "The Autopsy of Jane Doe",
  "Gerald's Game",
  "The Invisible Man",
  "Cam",
  "Mother!",
  "Wish Upon",
  "The Ritual",
  "The House on Haunted Hill",
  "The Haunting of Hill House",
  "Ghost Story",
  "The Thing",
  "The Eye",
  "The Descent",
  "The Autopsy of Jane Doe",
  "Gerald's Game",
  "The Invisible Man",
  "Cam",
  "Mother!",
  "Wish Upon",
  "The Ritual",
  "The House on Haunted Hill",
  "The Haunting of Hill House",
  "Ghost Story",
  "The Thing",
];
